export const PORT = 5000;
export const DEFAULT_TERMS_VERSION = "v1.0";

export const NOTIFICATION_TYPES = [
	"REGISTRATION_CONFIRMED",
	"EVENT_REMINDER",
	"FEEDBACK_REMINDER",
	"EVENT_APPROVED",
	"EVENT_REJECTED",
	"EVENT_SUBMITTED",
];